FROM satyadeep/php-53-fpm-alpine:latest

# modify www-data user to have id 1000
RUN sed -i 's/^www-data:x:[^:]*:/www-data:x:1000:/' /etc/passwd && \
    sed -i 's/^www-data:x:[^:]*:/www-data:x:1000:/' /etc/group

RUN apk add --no-cache nginx && mkdir -p /run/nginx && \
    ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

COPY php.ini /usr/local/etc/php/conf.d/php.ini
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --chown=www-data:www-data index.php /var/www/html
COPY --chmod=500 init.sh /init.sh

CMD ["/init.sh"]
